# Splunk Universal Forwarder - Endpoint Log Ingestion Rules
# Path: ./defensive-blue-team/splunk/inputs.conf

[default]
host = target-lan-node

# 1. Linux Authentication Records (For SSH Brute Force Detection)
[monitor:///var/log/auth.log]
disabled = false
index = network_logs
sourcetype = linux_secure
current_day_only = false

# 2. Corporate Web Server Access Logs (For SAMAMTV Web Exploitation Detection)
[monitor:///var/log/apache2/access.log]
disabled = false
index = web_logs
sourcetype = access_combined
_rcvbuf = 1572864

# 3. Host Shell Histories (Auditing Post-Exploitation Commands)
[monitor:///home/*/.bash_history]
disabled = false
index = network_logs
sourcetype = bash_history

[monitor:///root/.bash_history]
disabled = false
index = network_logs
sourcetype = bash_history
